server:
  port: 9090

file:
  resource:
    prefix: /profile
    path: D:/cloud_blog/upload
    content:
      avatar: /avatar
      defaultCover: /system/create/defaultCover

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${blog.db.host}:3306/cloud_blog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${blog.db.user}
    password: ${blog.db.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${blog.openai.api-key}
      base-url: ${blog.openai.base-url}
      chat:
        options:
          model: qwen3-vl:235b
      #          model: deepseek-v3.1:671b
      embedding:
        base-url: ${blog.openai.embedding.base-url}
        options:
          model: mxbai-embed-large:335m
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: embedded
#            schema: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-@@platform@@.sql
  sql:
    init:
      platform: mysql
#      schema-locations: classpath:
#      mode: always

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

elasticsearch:
  server:
    host: ${blog.es.host}
    port: ${blog.es.port}
    protocol: ${blog.es.protocol}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.cloudblog.user.mapper: debug
    org.apache.ibatis: debug
    org.mybatis: debug
    org.apache.ibatis.jdbc.ScriptRunner: debug
    org.apache.ibatis.transaction.managed.ManagedTransaction: debug
    com.baomidou.mybatisplus.core.executor: debug
    com.baomidou.mybatisplus.extension.plugins: debug


