server:
  port: 9090

file:
  resource:
    prefix: /profile
    path: D:/cloud_blog/upload
    content:
      avatar: /avatar
      defaultCover: /system/create/defaultCover

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${blog.db.host}:3306/cloud_blog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${blog.db.user}
    password: ${blog.db.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${blog.openai.api-key}
      base-url: ${blog.openai.base-url}
      chat:
        options:
          model: gemini-3-flash-preview
      #          model: deepseek-v3.1:671b
      embedding:
        base-url: ${blog.openai.embedding.base-url}
        options:
          model: mxbai-embed-large:335m
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: embedded
#            schema: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-@@platform@@.sql
  sql:
    init:
      platform: mysql
#      schema-locations: classpath:
#      mode: always

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: ${blog.redis.host}
      port: ${blog.redis.port}
      password: ${blog.redis.password}
      database: ${blog.redis.database}
      timeout: ${blog.redis.timeout}
      lettuce:
        pool:
          max-active: ${blog.redis.lettuce.pool.max-active}
          max-idle: ${blog.redis.lettuce.pool.max-idle}
          min-idle: ${blog.redis.lettuce.pool.min-idle}
          max-wait: ${blog.redis.lettuce.pool.max-wait}


elasticsearch:
  server:
    host: ${blog.es.host}
    port: ${blog.es.port}
    protocol: ${blog.es.protocol}
    index: ${blog.es.index}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# rsa密钥生成命令 keytool -genkeypair -alias cloudblog -keyalg RSA -keypass cloudblog -keystore cloudblog.jks -storepass cloudblog
# CN=fanxiaotong, OU=cloudblog, O=cloudblog, L=china, ST=hebei, C=cn
cloudblog:
  jwt:
    location: classpath:cloudblog.jks
    alias: ${blog.jwt.alias}
    password: ${blog.jwt.password}
    tokenTTL: ${blog.jwt.tokenTTL}
  auth:
    excludePaths:
      - /profile/**     # 静态资源
      - /ws/**          # websocket
      - /user/**
      - /userInfo/detail/**
      - /userInfo/homePage/**
      - /content/category/**
      - /content/checkCode/**
      - /content/comment/**
      - /content/focus/getFollowStatus
      - /content/focus/getFocusAndFansList
      - /content/Interest/**
      - /content/level/**
      - /content/post/**
      - /search/**
      - /content/share/**
      - /content/vip/getUserVipInfo
  default:
    avatar: ${blog.default.avatar}
    password: ${blog.default.password}
logging:
  level:
    com.cloudblog.user.mapper: debug
    org.apache.ibatis: debug
    org.mybatis: debug
    org.apache.ibatis.jdbc.ScriptRunner: debug
    org.apache.ibatis.transaction.managed.ManagedTransaction: debug
    com.baomidou.mybatisplus.core.executor: debug
    com.baomidou.mybatisplus.extension.plugins: debug


