blog:
  db:
    host: 192.168.19.129
    user: root
    pw: 123
  openai:
    api-key: 3fb46bb85efb47f986290974cc7519ec.ms4DPcnj1rnPSc_zGQD9ubU5
    base-url: https://ollama.com
    embedding:
      base-url: http://localhost:11434
  es:
    host: 192.168.19.129
    port: 9200
    protocol: http